{{- if and .Values.config.security.enabled .Values.config.security.secret.create }}
{{- $username := .Values.config.security.basicAuth.username | default .Values.config.security.username -}}
{{- $password := .Values.config.security.basicAuth.password | default .Values.config.security.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.config.security.secret.name }}{{ .Values.config.security.secret.name }}{{ else }}{{ include "kannika-api.name" . }}{{ end }}
type: Opaque
data:
  {{- if $username }}
  {{ default "username" .Values.config.security.secret.usernameKey }}: {{ $username | b64enc }}
  {{- end }}
  {{- if $password }}
  {{ default "password" .Values.config.security.secret.passwordKey }}: {{ $password | b64enc }}
  {{- end }}
{{- end }}
