console:
  enabled: true

api:
  enabled: true
  config:
    operatorService:
      name: operator
      enabled: true

operator:
  enabled: true
  config:
    eventGateway:
      enabled: true

global:
  logging:
    # The format of the logs. Can be "json" or "text".
    format: "json"
    # The log level. Can be "error", "warn", "info", "debug", or "trace".
    level: "info"
  imagePullSecrets: []
  kubernetes:
    # Specifies which namespace to use for the resources (backups, etc.).
    # This is preferably a separate namespace from the installation namespace.
    namespace: ""
  # Maintenance mode configuration.
  maintenance:
    # Whether maintenance mode is enabled.
    # When enabled, the operator will stop reconciling backups and restores.
    enabled: false
    # Banner configuration.
    # The banner is displayed to users to communicate maintenance status.
    # The banner is shown regardless of whether maintenance mode is enabled.
    banner:
      # The message to display. Leave unset to hide the banner.
      message:
      # The severity of the banner. Can be "warning", "info", or "error".
      variant: "info"
